### PR TITLE
[MRG] Fixing scans check to make sure BTI and CTF data work (directory based files for MEG)

### LINKED ISSUE #1002: Problem with error in scans.tsv matching for directory-based datasets (BTI, CTF, ...)
**Summary**
In the recent PR #976 scans in the scans.tsv file are matched against files found in the system. However, this for some reason breaks when doing BTI and CTF data.

See mne-bids related issue: https://github.com/mne-tools/mne-bids/issues/459

BTI and CTF data are unique because they nest another folder within the normal `<kind>/<fname>`, and their scans.tsv looks like `<kind>/<dir>/<fnames`. For some reason this breaks. 

**I am not sure  how to fix it, but I presume the lines here are problematic because they are storing a relativePath  that gets recursively gotten?** 

https://github.com/bids-standard/bids-validator/blob/9df173d9cf0fe84893ad5c615337de8b79287ff0/bids-validator/validators/tsv/tsv.js#L309-L312

**Misc questions**

**As I type this out, I'm not sure based on reading the specification, if this is a problem with how `mne-bids` is writing out the scans file for BTI/CTF/etc datasets that have this nested directory, or if it's a problem with the validator?**

**Example Output / Error**
For an example, check out the latest mne-bids and run `test_ctf` and `test_bti` unit tests.

The output is:

1. For BTI:

bids-validator error:

```
	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)

		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti/c,rf0.1Hz

			Evidence: c,rf0.1Hz

		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti/config

			Evidence: config

		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti/hs_file

			Evidence: hs_file
```

where the file structure looks like:

```
meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti	2012-09-23T11:51:38
├── sub-01
│   └── ses-01
│       ├── meg
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_events.tsv
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_channels.tsv
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.json
│       │   ├── sub-01_ses-01_acq-01_coordsystem.json
│       │   └── sub-01_ses-01_task-testing_acq-01_run-01_meg.bti
│       │       ├── config
│       │       ├── c,rf0.1Hz
│       │       └── hs_file
│       └── sub-01_ses-01_scans.tsv
├── dataset_description.json
├── participants.json
└── participants.tsv
```

and the scans.tsv contents are: `OrderedDict([('filename', ['meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.bti']), ('acq_time', ['2012-09-23T11:51:38'])])`

2. For CTF:

bids-validator error:
```
	1: [ERR] The filename in scans.tsv file does not match what is present in the BIDS dataset. (code: 129 - SCANS_FILENAME_NOT_MATCH_DATASET)

		./sub-01/ses-01/sub-01_ses-01_scans.tsv

			@ line: 1

			Evidence: Filename: /sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds

```

where the file structure looks like: 

```
meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds	2013-04-29T09:36:00
├── sub-01
│   └── ses-01
│       ├── meg
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_channels.tsv
│       │   ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.json
│       │   ├── sub-01_ses-01_acq-01_coordsystem.json
│       │   └── sub-01_ses-01_task-testing_acq-01_run-01_meg.ds
│       │       ├── BadChannels
│       │       ├── bad.segments
│       │       ├── params.dsc
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.res4
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.hc
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.infods
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.acq
│       │       ├── ClassFile.cls
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.newds
│       │       ├── sub-01_ses-01_task-testing_acq-01_run-01_meg.meg4
│       │       └── processing.cfg
│       └── sub-01_ses-01_scans.tsv
├── dataset_description.json
├── participants.json
└── participants.tsv
```

and the scans.tsv file has contents: `OrderedDict([('filename', ['meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds']), ('acq_time', ['2013-04-29T09:36:00'])])`

### PR DESCRIPTION
**Pull request by adam2392**
Closes: #1002 

I'm not an  expert w/ MEG data, and I don't even work with it, but there was a related issue with the validator issuing an error in `mne-bids` when writing BTI and CTF data. I updated the unit tests and the validator on `scans.tsv` to account for this behavior.

### CODE REVIEW

**Comment by adam2392** [comment]
Any update on this being mergable?

**Comment by sappelhoff** [comment]
> Any update on this being mergable?

Let's wait until it's a weekday again. I hope that @rwblair or @nellh can have a look and judge it.

File: bids-validator/validators/tsv/tsv.js [hunk 1]
```diff
@@ -305,11 +305,34 @@ const TSV = (file, contents, fileList, callback) => {
...
-    }
+      const fPath = fileList[f].relativePath
+      
+      // XXX: needs to be improved, since this currently allows arbitrary directory nesting
+      // dataset file needs to be within the subject
+      // and session directory
+      if (fPath.startsWith(subRelativePath)) {
+        if (fPath.includes('.ds/') || fPath.includes('_meg/')) {
+          // CTF or BTI data
+          var fDir = String(path.dirname(fPath))
```
Comment (nellh) [inline bids-validator/validators/tsv/tsv.js]: The String constructor here should be redundant, is there a reason it's needed?

File: bids-validator/validators/tsv/tsv.js [hunk 2]
```diff
@@ -305,11 +305,34 @@ const TSV = (file, contents, fileList, callback) => {
   }
 
   if (file.name.endsWith('_scans.tsv')) {
-    // create full dataset path list
+    // get the directory path for the scans.tsv
+    const scanDirPath = path.dirname(file.relativePath)
```
Comment (nellh) [inline bids-validator/validators/tsv/tsv.js:309]: I like using the path module for path manipulation more, we have a lot of manual path manipulation around the validator that is error prone. I wrote some comments in https://github.com/bids-standard/bids-validator/pull/976#pullrequestreview-438795376 about some possible issues with it.

File: bids-validator/tests/tsv.spec.js [hunk 3]
```diff
@@ -219,6 +295,23 @@ describe('TSV', function() {
     })
   })
 
+  it('should allow session missing', function() {
+    var niftiNoSesFile = {
+      name: 'sub-08_task-linebisection_run-01_bold.nii.gz',
+      relativePath: '/sub-08/func/sub-08_task-linebisection_run-01_bold.nii.gz',
+    }
+    var scansNoSesFile = {
```
Comment (nellh) [inline bids-validator/tests/tsv.spec.js:303]: There's no reason for any of the `var` usage in this PR, we should replace it with `const` to be consistent. A lot of the older validator code was written for early versions of Node.js where var was the only option but we've long since dropped support for those versions of Node.

File: bids-validator/validators/tsv/tsv.js [hunk 4]
```diff
@@ -305,11 +305,34 @@ const TSV = (file, contents, fileList, callback) => {
...
+
+    // get the subject and session for this scans.tsv file
+    const subject = file.name.split('_').slice(0, 1)
+    
+    // get the relative subject path
+    const subRelativePath = '/' + subject
+
+    // get list of file paths for this subject and session
     const pathList = []
     for (let f in fileList) {
```
Comment (nellh) [inline bids-validator/validators/tsv/tsv.js]: This is from #976 but this should be `for ... of Array.from(fileList)` to avoid bugs if fileList has properties that are not files.

**Review by nellh — CHANGES_REQUESTED** [review]
Functional change here looks good to me, just some minor code quality improvements requested. The path module question I'll file as a new issue for since there are examples of it prior to this and #976, I don't think it should block this.

File: bids-validator/validators/tsv/tsv.js (hunk 2 above)
Comment (adam2392) [reply bids-validator/validators/tsv/tsv.js:309]: Not sure what you mean here. I'm reading that this is preliminarily okay, but will get addressed in the issue #1007 ?

Comment (nellh) [reply bids-validator/validators/tsv/tsv.js:309]: Yes, I thought it may have been introduced by #976 but the path module usage predates that PR and #1007 is a better place to address the issue.

**Comment by adam2392** [comment]
I'm not sure why the `cli.js` is failing :(

**Comment by nellh** [comment]
> I'm not sure why the `cli.js` is failing :(

It's because the tests/data/valid_dataset example dataset used in the CLI fails this test with an error now and I gave you some bad advice... Sorry about that, this isn't a FileList, it is actually an object with properties for each file under NodeJS.

This should fix things for both environments.

```javascript
    // get list of file paths for this subject and session
    const pathList = []
    for (let file of Object.values(fileList)) {
```

**Review by rwblair — APPROVED** [review]

**Review by nellh — APPROVED** [review]
