### PR TITLE
Prevent out-of-memory error

### LINKED ISSUE #677: Command line & browser validator getting stuck / running out of memory
Hi-- I validated a data set with the in-browser tool. After I made the changes it called for, the validator stopped working for that dataset (works for other datasets).  Changes I made: (1) appended TR info to json files and (2) changed session folder names from ses-1(uniquenumbers) to just ses-1, (3) I renamed anat/my_T1_defaced.nii to subject appropriate names like 'sub-005_ses-18621_T1w.nii' & matched the sidecar.
When I try to validate the folder now it just gets stuck. The web runs for ~10 min then crashes my browser. I let the command line version run over an hour it gave a memory error (pasted below). My dataset is 24.23 GB. Any idea what I could have done that would be causing it to get stuck? It ran fine 4 other times on this folder. Thanks in advance!

I ran this with the actual path (also tried it without any flag options):
bids-validator --verbose --json /PATH/TO/Stanford_MASC/Nifti

Error:
```
<--- Last few GCs --->

[770:0x104800000]  3080259 ms: Mark-sweep 1318.5 (1325.0) -> 1318.5 (1324.5) MB, 8.3 / 0.0 ms  (average mu = 1.000, current mu = 0.002) last resort GC in old space requested
[770:0x104800000]  3080268 ms: Mark-sweep 1318.5 (1324.5) -> 1318.5 (1324.5) MB, 9.0 / 0.0 ms  (average mu = 0.999, current mu = 0.001) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xc27729dbe3d]
Security context: 0x31b061f88bc9 <JSObject>
    1: stringSlice(aka stringSlice) [0x31b0c1524621] [buffer.js:594] [bytecode=0x31b0c15587e1 offset=91](this=0x31b0738826f1 <undefined>,buf=0x31b061ff0cc9 <Uint8Array map = 0x31b074551eb1>,encoding=0x31b061f9e071 <String[4]: utf8>,start=0,end=48759136)
    2: toString [0x31b0b34f1cd1] [buffer.js:667] [bytecode=0x31b0c15582d1 offset=145](this=0x31b061ff0cc9 <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x10003b125 node::Abort() [/usr/local/bin/node]
 2: 0x10003b32f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001a8e85 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1005742a2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x10057d7a4 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 6: 0x10054f594 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: 0x10054f1d9 v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 8: 0x1001cb228 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/usr/local/bin/node]
 9: 0x1000ddc1a node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/usr/local/bin/node]
10: 0x100053f9b void node::Buffer::(anonymous namespace)::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: 0x10023170f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
12: 0x100230c51 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
13: 0x1002302f0 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0xc27729dbe3d 
Abort trap: 6
```

### PR DESCRIPTION
**Pull request by david-nishi**
Closes #677 

* [x] partial-load files for 0kb check
  * [x] in node
  * [x] in browser
* [x] limit concurrency in validators

### CODE REVIEW

File: validators/json/load.js [hunk 1]
```diff
@@ -1,30 +1,55 @@
 const utils = require('../../utils')
 
+function validate({
```
Comment (olgn) [inline validators/json/load.js]: what is the reason for adding validate() function (with six arguments) here? it adds ~15 lines of code

Comment (david-nishi) [reply validators/json/load.js]: was done to reduce complexity (codeclimate), the extra 15 lines of code are mostly the arguments/params eslint formatted into vertical lists

Comment (nellh) [reply validators/json/load.js]: I think this is worth refactoring further for clarity. Proposed version here https://github.com/DaNish808/bids-validator/pull/1

File: utils/files/validateMisc.js [hunk 2]
```diff
@@ -1,25 +1,20 @@
...
-      }),
-    ],
-    [],
-  )
-  return (
-    Promise.all(issuePromises)
-      // remove non-issues
-      .then(res => res.filter(o => o instanceof Issue))
+  return new Promise(resolve =>
+    resolve(miscFiles.map(createIssueForEmpty).filter(clearNonIssues)),
```
Comment (nellh) [inline utils/files/validateMisc.js]: This can just be `return Promise.resolve(miscFiles.map(createIssueForEmpty).filter(clearNonIssues))`

File: validators/json/load.js (hunk 1 above)
Comment (david-nishi) [reply validators/json/load.js]: merged

**Review by nellh — APPROVED** [review]
